### PR TITLE
Optimize and standardize code

### PR DESCRIPTION
**Pull request by mateusalexandre**

### CODE REVIEW

**Comment by icetee** [comment]
Please fix the CRLF / LF (new line), the whole file has been modified this way, not seeing the difference changes.

**Comment by mateusalexandre** [comment]
> Please fix the CRLF / LF (new line), the whole file has been modified this way, not seeing the difference changes.

Yep! There is already a blank line at the end CRLF / LF (new line), the github hides by default.

**Comment by mateusalexandre** [comment]
@icetee Btw, I noticed that you put the "hacktoberfest-accepted" tag on the project. But it is also necessary to add the tag "hacktoberfest" to be accepted. :+1:

**Comment by icetee** [comment]
In fact, it did not add any substantive change. Or not to see, sorry. I closed this PR.

**Pull request closed without merging**
